twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig','form/ja_theme.html.twig']
    paths:
        '%kernel.project_dir%/public/mail/css': css
    globals:
        imprint: '%env(imprint)%'
        dataPrivacy: '%env(dataPrivacy)%'
        helpUrl: '%env(helpUrl)%'
        helpUrlParticipants: '%env(helpUrlParticipants)%'
        laf_version: '%env(laF_version)%'
        matomo_enable: '%env(matomo_enable)%'
        matomo_id: '%env(matomo_id)%'
        matomo_url: '%env(matomo_url)%'
        laf_bbb: '%env(laF_bbb)%'
        laF_baseUrl: '%env(laF_baseUrl)%'
        laF_emailTextLogin: '%env(laF_emailTextLogin)%'
        laf_CreateServerOpenToEveryone: '%env(laf_CreateServerOpenToEveryone)%'
        laf_keycloakGroupToCreateServer: '%env(laf_keycloakGroupToCreateServer)%'
        laf_administratorEmail: '%env(laf_administratorEmail)%'
        laf_notificationUrl: '%env(laf_notificationUrl)%'
        laf_bbb_Url: '%env(laf_bbb_Url)%'
        laf_showName: '%env(laf_showName)%'
        laf_showNameFrontend: '%env(laf_showNameFrontend)%'
        laf_showNameInConference: '%env(laf_showNameInConference)%'
        laf_addParticipantsNoInput: '%env(laf_addParticipantsNoInput)%'
        laf_roomsMoreOptionsCollapsed: '%env(laf_roomsMoreOptionsCollapsed)%'
        laf_lobby_ReKnockTime: '%env(laf_lobby_ReKnockTime)%'
        laf_show_resendInvitation: '%env(laf_show_resendInvitation)%'
        input_settings_allow_sheduling: '%env(input_settings_allow_sheduling)%'
        input_settings_allow_roomPlanning: '%env(input_settings_allow_roomPlanning)%'
        dropdown_settings_common_share_links: '%env(dropdown_settings_common_share_links)%'
        dropdown_settings_common_delete: '%env(dropdown_settings_common_delete)%'
        dropdown_settings_common_edit: '%env(dropdown_settings_common_edit)%'
        dropdown_settings_common_duplicate: '%env(dropdown_settings_common_duplicate)%'
        dropdown_settings_series_edit_one: '%env(dropdown_settings_series_edit_one)%'
        dropdown_settings_series_edit_all: '%env(dropdown_settings_series_edit_all)%'
        dropdown_settings_series_type: '%env(dropdown_settings_series_type)%'
        dropdown_settings_series_delete: '%env(dropdown_settings_series_delete)%'
        dropdown_settings_series_delete_one: '%env(dropdown_settings_series_delete_one)%'
        dropdown_settings_mail_to_all: '%env(dropdown_settings_mail_to_all)%'
        dropdown_settings_series_new: '%env(dropdown_settings_series_new)%'
        dropdown_settings_start_browser: '%env(dropdown_settings_start_browser)%'
        dropdown_settings_start_app: '%env(dropdown_settings_start_app)%'
        dropdown_settings_shedule_planer: '%env(dropdown_settings_shedule_planer)%'
        dropdown_settings_shedule_share_links: '%env(dropdown_settings_shedule_share_links)%'
        dropdown_settings_shedule_delete: '%env(dropdown_settings_shedule_delete)%'
        dropdown_settings_shedule_edit: '%env(dropdown_settings_shedule_edit)%'
        dropdown_settings_shedule_mail_to_all: '%env(dropdown_settings_shedule_mail_to_all)%'
        dropdown_settings_generate_report: '%env(dropdown_settings_generate_report)%'
        start_dropdown_allow_browser: '%env(start_dropdown_allow_browser)%'
        start_dropdown_allow_app: '%env(start_dropdown_allow_app)%'
        helpText: '%env(helpText)%'
        laf_refreshTimeDashboard: '%env(laf_refreshTimeDashboard)%'
        laf_darkmodeAsDefault: '%env(laf_darkmodeAsDefault)%'
        allowTimeZoneSwitch: '%env(allowTimeZoneSwitch)%'
        JITSI_MEET_DEFAULT_TILE_VIEW: '%env(JITSI_MEET_DEFAULT_TILE_VIEW)%'
        JITSI_MEET_DEFAULT_PARTICIPANTS_PANE: '%env(JITSI_MEET_DEFAULT_PARTICIPANTS_PANE)%'
        laf_lobby_popUpDuration: '%env(laf_lobby_popUpDuration)%'
        WHITEBOARD_URL: '%env(WHITEBOARD_URL)%'
        LIVEKIT_BASE_URL: '%env(LIVEKIT_BASE_URL)%'